[[redirects]]
  from = "/*"
  to = "/frontend/public/index.html"
  status = 200

[build]
  command = "npm run build"
  publish="dist"
  base="frontend"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/.netlify/functions/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[context.production.environment]
  VUE_APP_BASEURL = "https://655e41b1c10ef30008a2d8dc--cicek-servise.netlify.app/"